### PR TITLE
Tgaugry proto autodoc

### PR DESCRIPTION
**Pull request by marques-bruno**
conflicts from #3 solved

### CODE REVIEW

**Comment by marques-bruno** [comment]
[ci-build]

**Comment by marques-bruno** [comment]
[ci-build]

**Comment by marques-bruno** [comment]
[ci-build]

**Comment by marques-bruno** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
I close the PR as it is getting old. I set he post-pone tag to keep it in under the hood.

**Pull request closed without merging**
