### PR TITLE
Adds the bindings of FileRepository

### PR DESCRIPTION
**Pull request by jnbrunet**
With this PR, you should now be able to create file repositories, and access the Sofa's global repositories `PluginRepository` and `DataRepository`

Example of a typical use:

```
import Sofa.Helper
import SofaRuntime
Sofa.Helper.PluginRepository.addFirstPath("/home/jnbrunet/sources/sofa/build/lib")
SofaRuntime.importPlugin("SofaAllCommonComponents")
```

Edit:

Global variables are now in `SofaRuntime`, so the example above is now:
```
import Sofa.Helper
import SofaRuntime
SofaRuntime.PluginRepository.addFirstPath("/home/jnbrunet/sources/sofa/build/lib")
SofaRuntime.importPlugin("SofaAllCommonComponents")
```

### CODE REVIEW

**Comment by marques-bruno** [comment]
Thanks for your contribution!
Could one of the admins verify this patch?

**Comment by jnbrunet** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
Hi @jnbrunet 

What about moving that into SofaRuntime ? 

On one side I think it is important to separate "one day" in sofa the stuff that rely on internal singletons and expose that in a separated namespace (eg: SofaRuntime). 

On the other side i think it make sense to stick to the existing Sofa API. 

What is your opinion ?

**Comment by jnbrunet** [comment]
Hey @damienmarchal 

I agree with you. I propose to meet at the middle here: **Sofa::helper::system::FileRepository** is a simple helper class here, so I think it should stay in sofa's namespace. The global variables `PluginRepository` and `DataRepository` should, in my opinon, be outside of sofa, probably initialized by the application (runSofa) and not made global to everyone using the Sofa framework. Hence, I moved those two in the `SofaRuntime`, even tho they are in the sofa's namespace normally.

**Pull request merged**
