### PR TITLE
Meshing and caching

### PR DESCRIPTION
**Pull request by sescaida**
Hey guys,

this PR addresses typical meshing tasks that arise when dealing with geometries intended for use in SOFA-scenes. The idea is to automate the meshing process for parametric geometries (step, brep, etc.) and surface meshes (.stl, obj, etc.), which come from a previous geometric design, modeling or scanning process. This PR profits from the availability of python3-bindings for Gmsh and CGAL. In Ubuntu 19 and later these are available through the package manager (python3-gmsh and python3-pygalmesh). Therefore, I've created some modules that will hopefully be useful as part of SPLIB in SofaPython3. The meshing process can be triggered directly from within any SOFA-scene.

There are three contributions in this PR:

1) A bridge to generate surface and volumetric meshes from parametric geometries using the python3-bindings of Gmsh. The user can set all available meshing options in Gmsh through the module.

2) A bridge to generate  volumetric meshes from surface meshes using the python3 module for CGAL. The user can set the available meshing options through the module.

3) A caching system that checks whether a target file (meshing output) has already been create from a source file and a given parameter set (parametric or surface mesh and meshing options). Beyond that, this caching system is intended to be generic, i.e. it could be useful for other file-types as well.

Let me know what you think! 

Best

Stefan

### CODE REVIEW

**Comment by sescaida** [comment]
This PR also includes a modification of the CMake-code to deal with a compiler flag when using Clang, which I needed to compile on my system.

**Comment by marques-bruno** [comment]
Thanks @sescaida for this contrib!

**Comment by jnbrunet** [comment]
Thanks @sescaida , this is awesome and will be very useful.

Just a few suggestion/comments:

- For CGAL, I think its missing one very useful feature: mesh local and global optimizers (ODT, Lloyd, perturber and exudation). Are the CGAL bindings providing an interface to these options?  
- It would be nice to have a fileless implementation (you can use Python's tempfile module for that) where you provide a meshio instance for example, and it gives you back another meshio with the volumetric mesh.
- Adding a verbose option to disable all prints if we don't need them (these prints can add a lot of noise when you are recording the output of many experiments and don't need/care for these one).

For the optimizers and fileless options, you can have a look at my old script that was using another CGAL bindings but should not be too far from the one you used:

https://gist.github.com/jnbrunet/b4a255de638efe8a4d25f545eaf9a872

**Comment by sescaida** [comment]
Hi @jnbrunet , thanks for your comments, I will improve the PR! 

> Just a few suggestion/comments:
> 
>     * For CGAL, I think its missing one very useful feature: mesh local and global optimizers (ODT, Lloyd, perturber and exudation). Are the CGAL bindings providing an interface to these options?
> 

These options are exposed in the interface as well. I didn't 

>     * It would be nice to have a fileless implementation (you can use Python's tempfile module for that) where you provide a meshio instance for example, and it gives you back another meshio with the volumetric mesh.
> 
>     * Adding a verbose option to disable all prints if we don't need them (these prints can add a lot of noise when you are recording the output of many experiments and don't need/care for these one).
> 
> 
> For the optimizers and fileless options, you can have a look at my old script that was using another CGAL bindings but should not be too far from the one you used:
> 
> https://gist.github.com/jnbrunet/b4a255de638efe8a4d25f545eaf9a872

**Comment by damienmarchal** [comment]
Hello @sescaida,

Can you do the PR to sofa-framework/plugins.SofaPython3 it is where sofa python is hosted now.

**Comment by sescaida** [comment]
> Hello @sescaida,
> 
> Can you do the PR to sofa-framework/plugins.SofaPython3 it is where sofa python is hosted now.

Sure,  I'm working on the feedback of @jnbrunet and once it's done I will make the PR again.

**Pull request closed without merging**
