### PR TITLE
Refactor and standardization of the build process.

### PR DESCRIPTION
**Pull request by jnbrunet**
Alright, here we go. This PR mainly adds two CMake tools function:

- **SP3_add_python_package(PACKAGE_NAME SOURCE_DIRECTORY TARGET_DIRECTORY)**
This function can be used to copy a given package directory to the target python packages directory. The copied files are first configure in the CMake way (@variable_names@ will be replaced by cmake variable of the same name).

- **SP3_add_python_module(TARGET MODULE_NAME DESTINATION SOURCES PYTHON_VERSION DEPENDS QUIET)**
This function can be used to compile a python module with pybind11 and output the resulting module library into the destination folder (usually the package recently created with SP3_add_python_package)

The source structure of the bindings is now also uniform :
    `bindings/SofaTypes/src/pybind/*` **=>** `bindings/SofaTypes/src/SofaPython3/SofaTypes`
    `bindings/SofaRuntime/src/pybind/*` **=>**  `bindings/SofaRuntime/src/SofaPython3/SofaRuntime`

Which allows the use of `#include <SofaPython3/SofaRuntime/*.h>`.

The `build/etc/sofa/python.d/*` config files are replaced by the simple file  `build/etc/sofa/python.d/plugin.SofaPython3.bindings` which contain the path to the configured and installed packages (`build/lib/site-packages` for build tree, and `build/install/lib/site-packages` for install tree)

Resulting build tree after this PR:

```
build
├── cmake
│   ├── SofaPython3Config.cmake
│   └── SofaPython3ConfigVersion.cmake
├── CMakeCache.txt
├── cmake_install.cmake
├── etc
│   └── sofa
│       └── python.d
│           └── plugin.SofaPython3.bindings                    ==> /build/lib/site-packages
├── lib
│   ├── libSofaPython3.so
│   └── site-packages
│       ├── Sofa
│       │   ├── __init__.py
│       │   ├── Sofa.cpython-36m-x86_64-linux-gnu.so
│       │   ├── test.py
│       │   └── Types
│       │       ├── __init__.py
│       │       ├── RGBAColor.py
│       │       └── Vec3.py
│       ├── SofaRuntime
│       │   ├── __init__.py
│       │   └── SofaRuntime.cpython-36m-x86_64-linux-gnu.so
│       └── SofaTypes
│           ├── __init__.py
│           └── SofaTypes.cpython-36m-x86_64-linux-gnu.so
└── SofaPython3ConfigVersion.cmake
```

It's a little bit cleaner like that I think, and the source code does not get polluted by the compilation output.
What do you guys think?

### CODE REVIEW

**Comment by marques-bruno** [comment]
Sounds good to me :)
I think the SofaTypes folder is kind of deprecated, that's why no effort had been done to give it the same directory structure as the other modules.

**Comment by damienmarchal** [comment]
I Agree with bruno and you this is a important move. 
So thank for the PR jean nicolas.

Just I'm not sure having a build/etc/sofa/python.d/plugin.SofaPython3.bindings 
To me the idea of separating Sofa & SofaRuntime was to illustrate they are two different module and should behave as a test case that we can build extra binding (to bind component specific on in separated plugin) on top of the Sofa one. Will this work ?

**Comment by jnbrunet** [comment]
@damienmarchal  Yes this is still de case with this PR. The  `build/etc/sofa/python.d/plugin.SofaPython3.bindings` simply states the path to a directory containing python packages (in this case, `/build/lib/site-packages`). Similary to packages in `/usr/lib/python3.x/site-packages`, the packages in  `/build/lib/site-packages` ( right now Sofa and SofaRuntype) are "independents" python packages

**Comment by damienmarchal** [comment]
Hello @jnbrunet can you update the PR so I merge it. I assume it will take less time on your side than for me.

**Comment by jnbrunet** [comment]
Done

**Comment by damienmarchal** [comment]
Je merge...ça risque de piquer mais go.

**Comment by damienmarchal** [comment]
It does not link properly here.

**Pull request merged**
