### PR TITLE
Cmake refactoring

### PR DESCRIPTION
**Pull request by jnbrunet**
All right, this is a big one, but normally it won't change anything for SofaPython3 devs, only for those that want to link against it.

The CMake project should now be correctly divided into two "components", which are, **Plugin** and **Bindings**. The **Plugin** component have nothing special, it has only one target, the plugin. It now have its own CMakeLists.txt which makes it simpler to configure.

The **Bindings** component has multiple targets. You have the usual targets related to a binary ( for example, the target `Bindings.Sofa.Core` is for the *Core.cpython-37m-x86_64-linux-gnu.so* binary). But you also have interface targets that makes it easier to links to multiple bindings at once:

1. Interface target `Bindings.Sofa` that links against `Bindings.Sofa.*`.
2. Interface target `Bindings.Module` that links against `Bindings.Module.*`
3. Interface target `Bindings` that links against `Bindings.Sofa` and `Bindings.Module`

The reason for these interfaces are, I think, better explained with examples:

### Example 1
Suppose our project simply needs the binding of `Sofa.Core.Base`. We will now be able to do this with the following CMakeLists.txt file of our project.

```cmake
project(example)

find_package(pybind11 CONFIG REQUIRED)
find_package(SofaPython3 COMPONENTS Bindings REQUIRED)

pybind11_add_module(${PROJECT_NAME} SHARED example.cpp)

target_link_libraries(${PROJECT_NAME} PUBLIC pybind11::module)
target_link_libraries(${PROJECT_NAME} PUBLIC SofaPython3::Bindings.Sofa.Core)
```
and the source file
```cpp
#include <pybind11/pybind11.h>
#include <SofaPython3/Sofa/Core/Binding_BaseObject.h>

namespace py = pybind11;
PYBIND11_MODULE(Example, m) {
// Binding code goes here...
}
```

Now, in this example, we simply needed to link against `Bindings.Sofa.Core`. If we wanted to link against, let's say, `Bindings.Sofa.Core`, `Bindings.Sofa.Helper` and `Bindings.SofaGui`, we could either add them all to the list of linked targets, or use the **interface** target `SofaPython3::Bindings` that links against all bindings :

### Example 2
```cmake
project(example)

find_package(pybind11 CONFIG REQUIRED)
find_package(SofaPython3 COMPONENTS Bindings REQUIRED)

pybind11_add_module(${PROJECT_NAME} SHARED example.cpp)

target_link_libraries(${PROJECT_NAME} PUBLIC pybind11::module)
target_link_libraries(${PROJECT_NAME} PUBLIC SofaPython3::Bindings)
```
and the source file
```cpp
#include <pybind11/pybind11.h>
#include <SofaPython3/Sofa/Core/Binding_BaseObject.h>
#include <SofaPython3/Sofa/Helper/Binding_Vector.h>
#include <SofaPython3/SofaGui/Binding_BaseGui.h>

namespace py = pybind11;
PYBIND11_MODULE(Example, m) {
// Binding code goes here...
}
```

### Example 3
If we don't care about the bindings, but we need the SofaPython3 `Plugin`, then simply use the appropriate target:

```cmake
project(example)

find_package(SofaPython3 COMPONENTS Plugin REQUIRED)

add_library(${PROJECT_NAME} SHARED example.cpp)

target_link_libraries(${PROJECT_NAME} PUBLIC SofaPython3::Plugin)
```
and the source file
```cpp
#include <SofaPython3/SceneLoaderPY3.h>
class MySceneLoader : public SceneLoaderPY3 {
// Loader's code goes here...
}
```

Finally, if we need everything, then of course, you can still pull everything...
### Example 4
```cmake
project(example)

find_package(pybind11 CONFIG REQUIRED)
find_package(SofaPython3 REQUIRED)

pybind11_add_module(${PROJECT_NAME} SHARED example.cpp)

target_link_libraries(${PROJECT_NAME} PUBLIC pybind11::module)
target_link_libraries(${PROJECT_NAME} PUBLIC SofaPython3::Plugin SofaPython3::Bindings)
```
and the source file
```cpp
#include <pybind11/pybind11.h>
#include <SofaPython3/Sofa/Core/Binding_BaseObject.h>
#include <SofaPython3/Sofa/Helper/Binding_Vector.h>
#include <SofaPython3/SofaGui/Binding_BaseGui.h>
#include <SofaPython3/PythonFactory.h>

namespace py = pybind11;

class MyComponent : public sofa::core::BaseObject {}

PYBIND11_MODULE(Example, m) {
    using namespace sofapython3;
    using sofa::core::objectmodel::Base;
// Binding code goes here...
   PythonFactory::registerType<MyComponent>([](Base* o) {
        return py::cast(dynamic_cast<MyComponent*>(o));
    });
}
```

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hello @jnbrunet 

Thank for this excellent PR. I have no time to review it in depth (and reviewing CMakeLists.txt :()) ...so I think I will trust your experience...merge it and debug problem when they will appear.

Will just way few days to give some time to @marques-bruno to reply

**Comment by marques-bruno** [comment]
Seems really cool, and way clearer / cleaner CMakeLists !
Since we still don't have a CI, I will try to test is today on my computer & test it with my SofaCV plugin and its bindings, see how It looks.
We should really fix the CI...

**Comment by jnbrunet** [comment]
Thanks @marques-bruno 

Yeah that would be great. In the meantime, I've run the tests on my pc and it seems that most of them pass, those that fail were still failing before this PR. 

Let me know when I can merge this.

**Comment by jnbrunet** [comment]
All right I will merge this as we have other PRs depending on this one coming up. Let me know if you hit any problems, I'll try to fix it as soon as possible.

**Pull request merged**
